import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { jsPDF } from "jspdf";
import { useAuth } from "@clerk/clerk-react";
import { ApiError, createBuilderResume, deleteBuilderResume, getBuilderResume, listBuilderResumes, updateBuilderResume } from "../services/api";
import { Plus, Trash2, Save, Eye, User, Briefcase, GraduationCap, Code2, FileText, Award, Loader2 } from "lucide-react";


type Experience={id:string;role:string;company:string;location:string;start:string;end:string;bullets:string[]};
type Education={id:string;school:string;degree:string;field:string;start:string;end:string};
type Project={id:string;name:string;link:string;description:string;technologies:string};
type ResumeData={name:string;title:string;email:string;phone:string;location:string;website:string;linkedin:string;summary:string;skills:string[];experience:Experience[];education:Education[];projects:Project[];achievements:string[]};
const blank:ResumeData={name:"",title:"",email:"",phone:"",location:"",website:"",linkedin:"",summary:"",skills:[],experience:[],education:[],projects:[],achievements:[]};
const uid=()=>Math.random().toString(36).slice(2,9);

export default function Builder(){
 const {getToken}=useAuth();
 const [data,setData]=useState<ResumeData>(blank); const [resumeId,setResumeId]=useState<number|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 const [section,setSection]=useState("personal"); const [preview,setPreview]=useState(false); const [saved,setSaved]=useState(false); const [dirty,setDirty]=useState(false); const [resumes,setResumes]=useState<Array<{id:number;name:string;template:string;data:Record<string,unknown>;created_at:string;updated_at:string}>>([]);
 const update=(key:keyof ResumeData,value:any)=>{setData(d=>({...d,[key]:value}));setDirty(true);setSaved(false)};
 const normalizeData=(raw:unknown):ResumeData=>{const d=(raw&&typeof raw==="object"?raw:{}) as Partial<ResumeData>;return {...blank,...d,skills:Array.isArray(d.skills)?d.skills.filter((x):x is string=>typeof x==="string"):[],experience:Array.isArray(d.experience)?d.experience:[],education:Array.isArray(d.education)?d.education:[],projects:Array.isArray(d.projects)?d.projects:[],achievements:Array.isArray(d.achievements)?d.achievements.filter((x):x is string=>typeof x==="string"):[]}};
 const validate=():string|null=>{if(!data.name.trim())return "Please enter your full name.";if(!data.email.trim())return "Please enter your email address.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim()))return "Please enter a valid email address.";return null};
 const confirmDiscard=()=>!dirty||window.confirm("You have unsaved changes. Discard them?");
 const loadResumes=async()=>{const token=await getToken();if(!token)return;const items=await listBuilderResumes(token);setResumes(items);return items};
 const newResume=()=>{if(!confirmDiscard())return;setResumeId(null);setData(blank);setSection("personal");setSaved(false);setDirty(false);setError(null)};
 const selectResume=async(id:number)=>{if(!confirmDiscard())return;try{const token=await getToken();if(!token)return;const result=await getBuilderResume(token,id);setResumeId(result.id);setData(normalizeData(result.data));setDirty(false);setSaved(false);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load resume.")}};
 const removeResume=async()=>{if(resumeId===null)return;if(!window.confirm("Delete this resume permanently?"))return;try{const token=await getToken();if(!token)return;await deleteBuilderResume(token,resumeId);const items=await loadResumes();if(items?.length){setResumeId(items[0].id);setData(normalizeData(items[0].data));setDirty(false)}else {setResumeId(null);setData(blank);setDirty(false)}}catch(e){setError(e instanceof ApiError?e.message:"Could not delete resume.")}};
 const save=async()=>{const validationError=validate();if(validationError){setError(validationError);setSection("personal");return}setSaving(true);setError(null);try{const token=await getToken();if(!token)throw new Error("Please sign in again.");const payload={name:data.name||"Untitled Resume",template:"ats-classic",data:data as unknown as Record<string,unknown>};const result=resumeId?await updateBuilderResume(token,resumeId,payload):await createBuilderResume(token,payload);setResumeId(result.id);await loadResumes();setDirty(false);setSaved(true);setTimeout(()=>setSaved(false),1600)}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:"Could not save resume.")}finally{setSaving(false)}};
 const download=()=>{
  const doc=new jsPDF({unit:"pt",format:"a4"});
  const left=42,maxWidth=511,bottom=770; let y=46;
  const ensure=(height:number)=>{if(y+height>bottom){doc.addPage();y=46}};
  const write=(value:string,size=9,bold=false,spacing=12)=>{
    if(!value?.trim())return;
    doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);
    const lines=doc.splitTextToSize(value.trim(),maxWidth) as string[];
    ensure(Math.max(spacing,lines.length*spacing));doc.text(lines,left,y);y+=lines.length*spacing;
  };
  const link=(label:string,url:string)=>{
    if(!url?.trim())return;
    const clean = url.trim().startsWith("http://") || url.trim().startsWith("https://") ? url.trim() : `https://${url.trim()}`;
    doc.setFont("helvetica","normal");doc.setFontSize(8);ensure(11);doc.textWithLink(label,left,y,{url:clean});y+=11;
  };
  const heading=(value:string)=>{ensure(24);y+=7;doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text(value.toUpperCase(),left,y);doc.setLineWidth(.5);doc.line(left,y+3,left+maxWidth,y+3);y+=14};
  write(data.name,18,true,20);
  write(data.title,11,true,14);
  const contacts=[data.email,data.phone,data.location].filter(Boolean).join(" • ");write(contacts,8,false,11);
  if(data.website)link("Website: "+data.website,data.website);
  if(data.linkedin)link("LinkedIn: "+data.linkedin,data.linkedin);
  if(data.summary){heading("Summary");write(data.summary,8,false,11)}
  if(data.experience.some(e=>e.role||e.company||e.bullets.some(Boolean))){heading("Experience");data.experience.forEach(e=>{write([e.role,e.company].filter(Boolean).join(" — "),9,true,12);write([e.location,[e.start,e.end].filter(Boolean).join(" — ")].filter(Boolean).join(" • "),8,false,11);e.bullets.filter(Boolean).forEach(b=>write("• "+b,8,false,11))})}
  if(data.projects.some(p=>p.name||p.description||p.technologies)){heading("Projects");data.projects.forEach(p=>{write(p.name,9,true,12);if(p.technologies)write("Technologies: "+p.technologies,8,false,11);if(p.description)write(p.description,8,false,11);if(p.link)link("Project: "+p.link,p.link)})}
  if(data.education.some(e=>e.school||e.degree||e.field)){heading("Education");data.education.forEach(e=>{write(e.school,9,true,12);write([e.degree,e.field].filter(Boolean).join(" — "),8,false,11);write([e.start,e.end].filter(Boolean).join(" — "),8,false,11)})}
  if(data.skills.length){heading("Skills");write(data.skills.join(" • "),8,false,11)}
  if(data.achievements.length){heading("Achievements");data.achievements.filter(Boolean).forEach(a=>write("• "+a,8,false,11))}
  const filename=(data.name||"Resume").trim().replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"")||"Resume";
  doc.save(`${filename}_Resume.pdf`);
 };
 useEffect(()=>{let active=true;(async()=>{try{const token=await getToken();if(!token)return;const items=await listBuilderResumes(token);if(active){setResumes(items);const result=items[0];if(result){setResumeId(result.id);setData(normalizeData(result.data));setDirty(false)}}}catch(e){if(active)setError(e instanceof ApiError?e.message:"Could not load your saved resume.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[getToken]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler)},[dirty]);
 const addExp=()=>update("experience",[...data.experience,{id:uid(),role:"",company:"",location:"",start:"",end:"Present",bullets:[""]}]);
 const addEdu=()=>update("education",[...data.education,{id:uid(),school:"",degree:"",field:"",start:"",end:""}]);
 const addProject=()=>update("projects",[...data.projects,{id:uid(),name:"",link:"",description:"",technologies:""}]);
 const sections=[["personal","Personal Information",User],["summary","Summary",FileText],["experience","Experience",Briefcase],["education","Education",GraduationCap],["projects","Projects",Code2],["skills","Skills",FileText],["achievements","Achievements",Award]] as const;
 if(loading)return <div className="w-full min-h-[400px] flex items-center justify-center text-[#8a8f98]"><Loader2 className="w-5 h-5 animate-spin mr-2"/>Loading your resume...</div>;
 return (
  <div className="w-full py-2 sm:py-4">
   {error&&<div className="mb-4 rounded-lg border border-rose-900/50 bg-rose-950/20 px-4 py-3 text-sm text-rose-300">{error}</div>}
   <div className="mb-4 flex flex-wrap items-center gap-2 rounded-xl border border-[#23232a] bg-[#111114] p-2">
 <select value={resumeId??""} onChange={e=>e.target.value?selectResume(Number(e.target.value)):newResume()} className="min-w-[220px] flex-1 rounded-lg border border-[#2a2a32] bg-[#0d0d10] px-3 py-2 text-sm text-[#d1d5db] outline-none">
  <option value="">New resume</option>{resumes.map(r=><option key={r.id} value={r.id}>{r.name||"Untitled Resume"}</option>)}
 </select>
 <button type="button" onClick={newResume} className="px-3 py-2 rounded-lg border border-[#2a2a32] text-sm text-[#d1d5db] hover:bg-[#17171c]">+ New</button>
 {resumeId!==null&&<button type="button" onClick={removeResume} className="px-3 py-2 rounded-lg border border-rose-900/50 text-sm text-rose-300 hover:bg-rose-950/20">Delete</button>}
</div>
<div className="flex items-end justify-between gap-4 mb-6">
    <div><p className="text-xs uppercase tracking-wider text-[#6f7480] mb-2">Resume workspace</p><h1 className="text-2xl font-bold text-[#f5f5f7]">Resume Builder</h1><p className="text-sm text-[#8a8f98] mt-1">Create an ATS-friendly resume with a live preview.</p></div>
    <div className="flex gap-2"><button onClick={()=>setPreview(!preview)} className="lg:hidden px-3 py-2 rounded-lg border border-[#23232a] bg-[#111114] text-[#d1d5db] text-sm flex items-center gap-2"><Eye className="w-4 h-4"/>{preview?"Edit":"Preview"}</button><button onClick={download} className="px-4 py-2 rounded-lg border border-[#23232a] bg-[#111114] text-[#d1d5db] text-sm font-semibold mr-2">Download PDF</button><button onClick={save} disabled={saving} className="px-4 py-2 rounded-lg bg-[#5b8def] disabled:opacity-60 hover:bg-[#4f7df6] text-white text-sm font-semibold flex items-center gap-2"><Save className="w-4 h-4"/>{saving?"Saving...":saved?"Saved":dirty?"Save Resume":"Saved"}</button></div>
   </div>
   <div className="grid grid-cols-1 lg:grid-cols-[190px_minmax(0,1fr)_minmax(360px,0.85fr)] gap-4 items-start">
    {!preview&&<aside className="bg-[#111114] border border-[#23232a] rounded-xl p-2 lg:sticky lg:top-4">{sections.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={"w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-left text-sm transition-colors "+(section===id?"bg-[#17192a] text-[#6d95ff]":"text-[#8a8f98] hover:text-white hover:bg-[#17171c]")}><Icon className="w-4 h-4"/>{label}</button>)}</aside>}
    {!preview&&<Editor section={section} data={data} update={update} addExp={addExp} addEdu={addEdu} addProject={addProject}/>}
    <Preview data={data}/>
   </div>
  </div>
 );
}
function Field({label,value,onChange,placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><span className="block text-xs font-medium text-[#8a8f98] mb-1.5">{label}</span><input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-[#2a2a32] bg-[#0d0d10] px-3 py-2.5 text-sm text-[#f5f5f7] placeholder:text-[#565b66] focus:border-[#5b8def] outline-none"/></label>}
function Area({label,value,onChange,rows=5}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}){return <label className="block"><span className="block text-xs font-medium text-[#8a8f98] mb-1.5">{label}</span><textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-[#2a2a32] bg-[#0d0d10] px-3 py-2.5 text-sm text-[#f5f5f7] focus:border-[#5b8def] outline-none resize-y"/></label>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="bg-[#111114] border border-[#23232a] rounded-xl p-5 sm:p-6"><div className="mb-5 pb-4 border-b border-[#23232a]"><h2 className="font-semibold text-[#f5f5f7]">{title}</h2></div>{children}</motion.section>}
function Editor({section,data,update,addExp,addEdu,addProject}:{section:string;data:ResumeData;update:(k:keyof ResumeData,v:any)=>void;addExp:()=>void;addEdu:()=>void;addProject:()=>void}){
 if(section==="personal")return <Panel title="Personal Information"><div className="grid sm:grid-cols-2 gap-4"><Field label="Full name" value={data.name} onChange={v=>update("name",v)}/><Field label="Professional title" value={data.title} onChange={v=>update("title",v)}/><Field label="Email" value={data.email} onChange={v=>update("email",v)}/><Field label="Phone" value={data.phone} onChange={v=>update("phone",v)}/><Field label="Location" value={data.location} onChange={v=>update("location",v)}/><Field label="Website" value={data.website} onChange={v=>update("website",v)}/><Field label="LinkedIn" value={data.linkedin} onChange={v=>update("linkedin",v)}/></div></Panel>;
 if(section==="summary")return <Panel title="Professional Summary"><Area label="Summary" value={data.summary} onChange={v=>update("summary",v)} rows={9}/></Panel>;
 if(section==="skills")return <Panel title="Skills">
  <div className="space-y-4">
   <div className="flex gap-2">
    <input id="skill-input" placeholder="e.g. React, Python, SQL" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();const v=e.currentTarget.value.trim();if(v&&!data.skills.some(s=>s.toLowerCase()===v.toLowerCase())){update("skills",[...data.skills,v]);e.currentTarget.value=""}}}} className="flex-1 rounded-lg border border-[#2a2a32] bg-[#0d0d10] px-3 py-2.5 text-sm text-[#f5f5f7] placeholder:text-[#565b66] focus:border-[#5b8def] outline-none"/>
    <button type="button" onClick={()=>{const el=document.getElementById("skill-input") as HTMLInputElement|null;const v=el?.value.trim()||"";if(v&&!data.skills.some(s=>s.toLowerCase()===v.toLowerCase())){update("skills",[...data.skills,v]);if(el)el.value=""}}} className="px-4 rounded-lg bg-[#5b8def] hover:bg-[#4f7df6] text-white text-sm font-semibold">Add</button>
   </div>
   {data.skills.length===0?<p className="text-xs text-[#6f7480]">Add skills one at a time. Press Enter or Add.</p>:<div className="flex flex-wrap gap-2">{data.skills.map((skill,i)=><span key={skill+i} className="inline-flex items-center gap-2 rounded-full border border-[#30303a] bg-[#17171c] px-3 py-1.5 text-sm text-[#d1d5db]">{skill}<button type="button" aria-label={"Remove "+skill} onClick={()=>update("skills",data.skills.filter((_,j)=>j!==i))} className="text-[#777d88] hover:text-rose-400"><Trash2 className="w-3.5 h-3.5"/></button></span>)}</div>}
  </div>
 </Panel>;
 if(section==="achievements")return <Panel title="Achievements"><Area label="Achievements (one per line)" value={data.achievements.join("\n")} onChange={v=>update("achievements",v.split("\n").map(x=>x.trim()).filter(Boolean))} rows={8}/></Panel>;
 if(section==="experience")return <Panel title="Experience"><div className="space-y-4">{data.experience.map((e,i)=><div key={e.id} className="rounded-xl border border-[#23232a] bg-[#151519] p-4"><div className="flex justify-between mb-4"><b className="text-sm text-[#f5f5f7]">Experience {i+1}</b><button onClick={()=>update("experience",data.experience.filter(x=>x.id!==e.id))} className="text-[#8a8f98] hover:text-rose-400"><Trash2 className="w-4 h-4"/></button></div><div className="grid sm:grid-cols-2 gap-3"><Field label="Role" value={e.role} onChange={v=>update("experience",data.experience.map(x=>x.id===e.id?{...x,role:v}:x))}/><Field label="Company" value={e.company} onChange={v=>update("experience",data.experience.map(x=>x.id===e.id?{...x,company:v}:x))}/><Field label="Location" value={e.location} onChange={v=>update("experience",data.experience.map(x=>x.id===e.id?{...x,location:v}:x))}/><div className="grid grid-cols-2 gap-2"><Field label="Start" value={e.start} onChange={v=>update("experience",data.experience.map(x=>x.id===e.id?{...x,start:v}:x))}/><Field label="End" value={e.end} onChange={v=>update("experience",data.experience.map(x=>x.id===e.id?{...x,end:v}:x))}/></div></div><div className="mt-4 space-y-2"><span className="text-xs font-medium text-[#8a8f98]">Bullet points</span>{e.bullets.map((b,j)=><div key={j} className="flex gap-2"><input value={b} onChange={ev=>update("experience",data.experience.map(x=>x.id===e.id?{...x,bullets:x.bullets.map((z,k)=>k===j?ev.target.value:z)}:x))} className="flex-1 rounded-lg border border-[#2a2a32] bg-[#0d0d10] px-3 py-2 text-sm text-[#f5f5f7] outline-none"/><button onClick={()=>update("experience",data.experience.map(x=>x.id===e.id?{...x,bullets:x.bullets.filter((_,k)=>k!==j)}:x))} className="text-[#6f7480]"><Trash2 className="w-4 h-4"/></button></div>)}<button onClick={()=>update("experience",data.experience.map(x=>x.id===e.id?{...x,bullets:[...x.bullets,""]}:x))} className="text-xs text-[#6d95ff]">+ Add bullet</button></div></div>)}</div><button onClick={addExp} className="mt-4 w-full py-2.5 border border-dashed border-[#34343d] rounded-lg text-sm text-[#8a8f98] hover:text-white"><Plus className="w-4 h-4 inline mr-1"/>Add experience</button></Panel>;
 if(section==="education")return <Panel title="Education"><div className="space-y-4">{data.education.map(e=><div key={e.id} className="rounded-xl border border-[#23232a] bg-[#151519] p-4"><div className="flex justify-end"><button onClick={()=>update("education",data.education.filter(x=>x.id!==e.id))} className="text-[#8a8f98] hover:text-rose-400"><Trash2 className="w-4 h-4"/></button></div><div className="grid sm:grid-cols-2 gap-3"><Field label="School" value={e.school} onChange={v=>update("education",data.education.map(x=>x.id===e.id?{...x,school:v}:x))}/><Field label="Degree" value={e.degree} onChange={v=>update("education",data.education.map(x=>x.id===e.id?{...x,degree:v}:x))}/><Field label="Field" value={e.field} onChange={v=>update("education",data.education.map(x=>x.id===e.id?{...x,field:v}:x))}/><div className="grid grid-cols-2 gap-2"><Field label="Start" value={e.start} onChange={v=>update("education",data.education.map(x=>x.id===e.id?{...x,start:v}:x))}/><Field label="End" value={e.end} onChange={v=>update("education",data.education.map(x=>x.id===e.id?{...x,end:v}:x))}/></div></div></div>)}</div><button onClick={addEdu} className="mt-4 w-full py-2.5 border border-dashed border-[#34343d] rounded-lg text-sm text-[#8a8f98]"><Plus className="w-4 h-4 inline mr-1"/>Add education</button></Panel>;
 if(section==="projects")return <Panel title="Projects"><div className="space-y-4">{data.projects.map(p=><div key={p.id} className="rounded-xl border border-[#23232a] bg-[#151519] p-4"><div className="flex justify-end"><button onClick={()=>update("projects",data.projects.filter(x=>x.id!==p.id))} className="text-[#8a8f98] hover:text-rose-400"><Trash2 className="w-4 h-4"/></button></div><div className="space-y-3"><Field label="Project name" value={p.name} onChange={v=>update("projects",data.projects.map(x=>x.id===p.id?{...x,name:v}:x))}/><Field label="Project link" value={p.link} onChange={v=>update("projects",data.projects.map(x=>x.id===p.id?{...x,link:v}:x))}/><Field label="Technologies" value={p.technologies} onChange={v=>update("projects",data.projects.map(x=>x.id===p.id?{...x,technologies:v}:x))}/><Area label="Description" value={p.description} onChange={v=>update("projects",data.projects.map(x=>x.id===p.id?{...x,description:v}:x))} rows={4}/></div></div>)}</div><button onClick={addProject} className="mt-4 w-full py-2.5 border border-dashed border-[#34343d] rounded-lg text-sm text-[#8a8f98]"><Plus className="w-4 h-4 inline mr-1"/>Add project</button></Panel>;
 return null;
}

function Preview({data}:{data:ResumeData}){return <section className="bg-[#1a1a1f] border border-[#2a2a32] rounded-xl p-3 lg:sticky lg:top-4"><div className="flex justify-between px-2 pb-2"><span className="text-xs font-semibold uppercase tracking-wider text-[#8a8f98]">Live preview</span><span className="text-[10px] text-[#565b66]">ATS Classic</span></div><div className="bg-white text-black min-h-[720px] shadow-xl rounded-sm p-7 sm:p-9 text-[9px] leading-[1.45]"><h1 className="text-xl font-bold">{data.name||"Your Name"}</h1><p className="font-medium text-gray-700">{data.title||"Professional Title"}</p><p className="text-gray-500 mt-1">{[data.email,data.phone,data.location,data.website,data.linkedin].filter(Boolean).join(" • ")||"email@example.com • City, Country"}</p>{data.summary&&<Block title="SUMMARY"><p>{data.summary}</p></Block>}{data.experience.length>0&&<Block title="EXPERIENCE">{data.experience.map(e=><div key={e.id} className="mb-2"><div className="flex justify-between font-bold"><span>{e.role||"Role"} — {e.company||"Company"}</span><span>{e.start} {e.end&&"—"} {e.end}</span></div><ul className="list-disc pl-4">{e.bullets.filter(Boolean).map((b,i)=><li key={i}>{b}</li>)}</ul></div>)}</Block>}{data.projects.length>0&&<Block title="PROJECTS">{data.projects.map(p=><div key={p.id} className="mb-2"><b>{p.name||"Project"}</b>{p.technologies&&" — "+p.technologies}<p>{p.description}</p></div>)}</Block>}{data.education.length>0&&<Block title="EDUCATION">{data.education.map(e=><div key={e.id}><b>{e.school||"School"}</b> — {e.degree} {e.field&&"in "+e.field} <span>{e.start} — {e.end}</span></div>)}</Block>}{data.skills.length>0&&<Block title="SKILLS"><p>{data.skills.join(" • ")}</p></Block>}{data.achievements.length>0&&<Block title="ACHIEVEMENTS"><ul className="list-disc pl-4">{data.achievements.map((a,i)=><li key={i}>{a}</li>)}</ul></Block>}</div></section>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <div className="mt-4"><h2 className="font-bold border-b border-gray-400 pb-0.5 mb-1.5 tracking-wide">{title}</h2>{children}</div>}